stages:
 - build


before_script:
  - export LANG=UTF-8
  - env
  - locale


build_job:
  stage: build
  script: 
    - docker build -t vapor-image .
    - docker run --name vapor-server -p 8080:8080 vapor-image